project_id = "rvgrxtzqkygjxlwlmvvn"

[functions.extract-nf]
verify_jwt = false

[functions.analyze-provider-risk]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.pagarme-webhook]
verify_jwt = false

[functions.generate-invite]
verify_jwt = false
