# Generated by Django 5.2.12 on 2026-03-25 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='ABERTA')),
                ('priority', models.TextField(default='MEDIA')),
                ('is_emergency', models.BooleanField(default=False)),
                ('executor_type', models.TextField(blank=True, null=True)),
                ('final_pdf_url', models.TextField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider')),
            ],
            options={
                'db_table': 'service_orders',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.TextField(default='pendente')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('created_by_user', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider')),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('approver_role', models.TextField()),
                ('approval_type', models.TextField()),
                ('decision', models.TextField(default='pendente')),
                ('justification', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_minerva', models.BooleanField(default=False)),
                ('minerva_justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activity_type', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'service_order_activities',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'service_order_materials',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('photo_type', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(db_column='service_order_id', on_delete=django.db.models.deletion.CASCADE, to='condos.serviceorder')),
            ],
            options={
                'db_table': 'service_order_photos',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='aberto')),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='ticket',
            field=models.ForeignKey(blank=True, db_column='ticket_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='condos.ticket'),
        ),
    ]
