# Generated by Django 5.2.12 on 2026-03-25 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('issuer_name', models.TextField(blank=True, null=True)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('source_type', models.TextField(blank=True, null=True)),
                ('document_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='pendente')),
                ('approval_status', models.TextField(default='pendente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'fiscal_documents',
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('approver_role', models.TextField()),
                ('decision', models.TextField(default='pendente')),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_user', models.ForeignKey(db_column='approver_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('fiscal_document', models.ForeignKey(db_column='fiscal_document_id', on_delete=django.db.models.deletion.CASCADE, to='invoices.fiscaldocument')),
            ],
            options={
                'db_table': 'fiscal_document_approvals',
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stock_item_id', models.UUIDField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiscal_document', models.ForeignKey(db_column='fiscal_document_id', on_delete=django.db.models.deletion.CASCADE, to='invoices.fiscaldocument')),
            ],
            options={
                'db_table': 'fiscal_document_items',
            },
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'stock_categories',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.stockcategory')),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'stock_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('move_type', models.TextField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_order_id', models.UUIDField(blank=True, null=True)),
                ('service_order_material_id', models.UUIDField(blank=True, null=True)),
                ('fiscal_document_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='invoices.stockitem')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
    ]
