# Generated by Django 5.2.12 on 2026-03-25 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_create_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('invite_code', models.TextField(blank=True, null=True)),
                ('invite_active', models.BooleanField(default=False)),
                ('subscription_status', models.TextField(default='trial')),
                ('subscription_id', models.TextField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pagarme_customer_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'condos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('auth_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CondoFinancialConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approval_deadline_hours', models.IntegerField(default=48)),
                ('notify_residents_above', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.OneToOneField(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'condo_financial_config',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('document', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('unit_label', models.TextField(blank=True, null=True)),
                ('unit_id', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
            ],
            options={
                'db_table': 'residents',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('entity', models.TextField(blank=True, null=True)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='UserCondo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('status', models.TextField(default='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condo', models.ForeignKey(db_column='condo_id', on_delete=django.db.models.deletion.CASCADE, to='core.condo')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'user_condos',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
    ]
